name: oe-alliance plugins

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Build oe-alliance plugins
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        gcc: [11,13,14]
        python: ['3.10','3.11','3.12','3.13']
    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get -q update
          sudo apt-get install -y software-properties-common
          for i in {1..5}; do
            sudo add-apt-repository -y ppa:deadsnakes/ppa && break || sleep 10
          done
          sudo apt remove -y libunwind-14-dev
          sudo apt-get install -y g++-${{ matrix.gcc }} build-essential autoconf autotools-dev gettext python${{ matrix.python }}-dev libntirpc-dev

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Build plugins, gcc-${{ matrix.gcc }}, python ${{ matrix.python }}
        env:
          CC: "gcc-${{ matrix.gcc }}"
          CXX: "g++-${{ matrix.gcc }}"
        run: |
          pip3 install six
          autoreconf -i
          ./configure
          make
          python -m compileall .
